"""Context compression — summarize old messages when approaching token limits.

Long conversations eventually exceed the model's context window. This module
detects when that's about to happen and compresses older messages into a
summary, preserving recent context verbatim.

Strategy (simpler than Hermes' multi-stage compressor):
  1. Estimate token count of the message history (chars / 4 heuristic)
  2. When it exceeds the threshold (default 80% of model's limit), trigger
  3. Keep the N most recent messages verbatim (default 10)
  4. Summarize everything before that into a single "system" message
  5. Replace old messages with [summary + recent messages]

The summary is generated by the same model the agent uses — no separate
summarizer model. This is a deliberate tradeoff: simpler architecture at
the cost of one extra API call per compression.

Cache safety: compression only touches message_history, never the system
prompt. The system prompt stays byte-stable for the entire conversation.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)

# Heuristic: 1 token ≈ 4 chars for English text
_CHARS_PER_TOKEN = 4

# Default thresholds
DEFAULT_MODEL_CONTEXT = 128_000  # tokens (gpt-4o standard)
DEFAULT_COMPRESS_THRESHOLD = 0.80  # compress at 80% of context window
DEFAULT_KEEP_RECENT = 10  # keep this many recent messages verbatim
DEFAULT_MIN_MESSAGES_TO_COMPRESS = 20  # don't compress if fewer than this


def estimate_tokens(text: str) -> int:
    """Rough token estimate: chars / 4. Good enough for threshold checks."""
    return max(1, len(text) // _CHARS_PER_TOKEN)


def estimate_message_tokens(messages: list[dict[str, str]]) -> int:
    """Estimate total tokens in a message list."""
    total = 0
    for msg in messages:
        content = msg.get("content", "")
        total += estimate_tokens(content)
        # Each message has ~4 tokens of overhead (role, separators)
        total += 4
    return total


def should_compress(
    messages: list[dict[str, str]],
    *,
    model_context: int = DEFAULT_MODEL_CONTEXT,
    threshold: float = DEFAULT_COMPRESS_THRESHOLD,
    system_prompt_tokens: int = 0,
) -> bool:
    """Check if message history should be compressed.

    Args:
        messages: List of {'role': ..., 'content': ...} dicts
        model_context: Model's max context window in tokens
        threshold: Fraction of context window that triggers compression
        system_prompt_tokens: Tokens used by the system prompt (reserved)

    Returns:
        True if compression is needed
    """
    if len(messages) < DEFAULT_MIN_MESSAGES_TO_COMPRESS:
        return False

    available = model_context - system_prompt_tokens
    trigger_at = int(available * threshold)
    current = estimate_message_tokens(messages)
    return current > trigger_at


def split_messages(
    messages: list[dict[str, str]],
    *,
    keep_recent: int = DEFAULT_KEEP_RECENT,
) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    """Split messages into (to_compress, to_keep).

    Args:
        messages: Full message history
        keep_recent: Number of recent messages to keep verbatim

    Returns:
        (old_messages, recent_messages) tuple
    """
    if len(messages) <= keep_recent:
        return [], messages
    return messages[:-keep_recent], messages[-keep_recent:]


def build_summary_prompt(old_messages: list[dict[str, str]]) -> str:
    """Build the prompt for the summarizer model.

    Args:
        old_messages: Messages to summarize

    Returns:
        Prompt string for the summarizer
    """
    conversation = "\n\n".join(
        f"[{m['role']}]: {m['content'][:2000]}"  # cap each message at 2000 chars
        for m in old_messages
        if m.get("content")
    )

    return (
        "Summarize the following conversation history concisely. "
        "Preserve key facts, decisions, code snippets, and action items. "
        "Keep it under 500 words. Write as a factual summary, not dialogue.\n\n"
        f"--- CONVERSATION TO SUMMARIZE ---\n{conversation}\n--- END ---"
    )


def compress_messages(
    messages: list[dict[str, str]],
    summary: str,
    *,
    keep_recent: int = DEFAULT_KEEP_RECENT,
) -> list[dict[str, str]]:
    """Replace old messages with a summary + recent messages.

    Args:
        messages: Full message history
        summary: Generated summary text
        keep_recent: Number of recent messages to keep verbatim

    Returns:
        New message list: [summary_message, ...recent_messages]
    """
    _, recent = split_messages(messages, keep_recent=keep_recent)

    summary_msg = {
        "role": "system",
        "content": (
            "[Context Summary — earlier conversation compressed]\n\n"
            f"{summary}\n\n"
            "[End of Summary — recent messages follow]"
        ),
    }

    return [summary_msg] + recent


async def compress_if_needed(
    messages: list[dict[str, str]],
    *,
    model: Any = None,
    model_context: int = DEFAULT_MODEL_CONTEXT,
    threshold: float = DEFAULT_COMPRESS_THRESHOLD,
    system_prompt_tokens: int = 0,
    keep_recent: int = DEFAULT_KEEP_RECENT,
) -> list[dict[str, str]]:
    """Compress message history if it exceeds the threshold.

    If compression is not needed, returns the original messages unchanged.
    If compression is needed but no model is provided, returns the original
    messages with a warning (graceful degradation).

    Args:
        messages: Message history
        model: Pydantic AI model instance for generating the summary
        model_context: Model's max context window
        threshold: Compression trigger fraction
        system_prompt_tokens: Tokens reserved by system prompt
        keep_recent: Messages to keep verbatim

    Returns:
        Potentially compressed message list
    """
    if not should_compress(
        messages,
        model_context=model_context,
        threshold=threshold,
        system_prompt_tokens=system_prompt_tokens,
    ):
        return messages

    old, recent = split_messages(messages, keep_recent=keep_recent)
    if not old:
        return messages

    logger.info(
        "Compressing %d messages (keeping %d recent, est. %d tokens)",
        len(old),
        len(recent),
        estimate_message_tokens(messages),
    )

    if model is None:
        logger.warning("Compression needed but no model provided — skipping")
        return messages

    # Generate summary using the model
    summary_prompt = build_summary_prompt(old)
    try:
        from pydantic_ai import Agent

        summarizer = Agent(
            model=model,
            system_prompt="You are a conversation summarizer. Be concise and factual.",
        )
        result = await summarizer.run(summary_prompt)
        summary = result.output
    except Exception as e:
        logger.warning("Summary generation failed: %s — skipping compression", e)
        return messages

    compressed = compress_messages(messages, summary, keep_recent=keep_recent)
    logger.info(
        "Compressed: %d messages → %d (est. %d tokens)",
        len(messages),
        len(compressed),
        estimate_message_tokens(compressed),
    )
    return compressed


# ---------------------------------------------------------------------------
# Multi-strategy compression (advanced)
# ---------------------------------------------------------------------------

# Strategies available (in order of aggressiveness)
COMPRESSION_STRATEGIES = ["sliding_window", "importance", "semantic", "summarize"]


def _score_message_importance(msg: dict[str, str]) -> float:
    """Score a message by importance (0.0 - 1.0).

    Higher score = more important = should be kept verbatim.
    Factors: code blocks, tool calls, user decisions, length, recency.
    """
    content = msg.get("content", "")
    if not content:
        return 0.0

    score = 0.0

    # Code blocks are important
    if "```" in content:
        score += 0.3

    # Tool calls / function calls
    if '"tool_call"' in content or '"function_call"' in content:
        score += 0.2

    # Error messages
    if "error" in content.lower() or "traceback" in content.lower():
        score += 0.15

    # User decisions / instructions
    if msg.get("role") == "user":
        score += 0.2
        # Questions are important context
        if "?" in content:
            score += 0.1

    # System messages are always important
    if msg.get("role") == "system":
        score += 0.5

    # Longer messages may contain more context
    length_score = min(len(content) / 2000, 0.2)
    score += length_score

    return min(score, 1.0)


def compress_sliding_window(
    messages: list[dict[str, str]],
    *,
    keep_recent: int = DEFAULT_KEEP_RECENT,
) -> list[dict[str, str]]:
    """Sliding window strategy — keep only N most recent messages.

    Simplest strategy: drop everything except the last N messages.
    No summarization needed.
    """
    if len(messages) <= keep_recent:
        return messages
    return messages[-keep_recent:]


def compress_importance_based(
    messages: list[dict[str, str]],
    *,
    keep_recent: int = DEFAULT_KEEP_RECENT,
    keep_ratio: float = 0.5,
) -> list[dict[str, str]]:
    """Importance-based strategy — keep most important + recent messages.

    Scores each message by importance and keeps the top fraction,
    plus all recent messages.
    """
    if len(messages) <= DEFAULT_MIN_MESSAGES_TO_COMPRESS:
        return messages

    # Always keep recent messages
    old, recent = split_messages(messages, keep_recent=keep_recent)
    if not old:
        return messages

    # Score old messages
    scored = [(i, _score_message_importance(msg), msg) for i, msg in enumerate(old)]

    # Sort by score (descending) and keep top fraction
    scored.sort(key=lambda x: x[1], reverse=True)
    keep_count = max(1, int(len(old) * keep_ratio))
    kept = scored[:keep_count]

    # Sort kept messages back by original order
    kept.sort(key=lambda x: x[0])

    return [m for _, _, m in kept] + recent


def compress_semantic(
    messages: list[dict[str, str]],
    *,
    keep_recent: int = DEFAULT_KEEP_RECENT,
    model: Any = None,
) -> list[dict[str, str]]:
    """Semantic strategy — cluster messages by topic, keep representatives.

    Groups messages by topic similarity (simple keyword overlap) and
    keeps one representative per cluster plus all recent messages.
    """
    if len(messages) <= DEFAULT_MIN_MESSAGES_TO_COMPRESS:
        return messages

    old, recent = split_messages(messages, keep_recent=keep_recent)
    if not old:
        return messages

    # Simple keyword-based clustering
    clusters: list[list[int]] = []  # list of (message indices in old)
    cluster_keywords: list[set[str]] = []

    for i, msg in enumerate(old):
        content = msg.get("content", "").lower()
        words = set(content.split())
        # Filter out common words
        words -= {"the", "a", "an", "is", "are", "was", "were", "be", "been",
                   "have", "has", "had", "do", "does", "did", "will", "would",
                   "could", "should", "may", "might", "can", "to", "of", "in",
                   "on", "at", "by", "for", "with", "from", "and", "or", "but",
                   "not", "no", "yes", "i", "you", "he", "she", "it", "we",
                   "they", "this", "that", "these", "those"}

        # Find matching cluster
        matched = False
        for ci, kw in enumerate(cluster_keywords):
            if words & kw:  # overlap
                clusters[ci].append(i)
                cluster_keywords[ci] |= words
                matched = True
                break

        if not matched:
            clusters.append([i])
            cluster_keywords.append(words)

    # Keep the last message from each cluster (most recent in topic)
    kept_indices: list[int] = []
    for cluster in clusters:
        kept_indices.append(cluster[-1])  # most recent in cluster

    kept_indices.sort()
    kept_messages = [old[i] for i in kept_indices]

    return kept_messages + recent


async def compress_multi_strategy(
    messages: list[dict[str, str]],
    *,
    strategy: str = "summarize",
    model: Any = None,
    model_context: int = DEFAULT_MODEL_CONTEXT,
    threshold: float = DEFAULT_COMPRESS_THRESHOLD,
    system_prompt_tokens: int = 0,
    keep_recent: int = DEFAULT_KEEP_RECENT,
) -> list[dict[str, str]]:
    """Compress using the specified strategy.

    Strategies (least to most aggressive):
      - sliding_window: Keep only N recent messages (no summarization)
      - importance: Keep most important + recent messages (no summarization)
      - semantic: Cluster by topic, keep representatives + recent
      - summarize: Full summarization of old messages (default, most context preserved)

    Args:
        messages: Message history
        strategy: Compression strategy name
        model: Model for summarization (only needed for "summarize")
        model_context: Model's max context window
        threshold: Compression trigger fraction
        system_prompt_tokens: Tokens reserved by system prompt
        keep_recent: Messages to keep verbatim

    Returns:
        Potentially compressed message list
    """
    if not should_compress(
        messages,
        model_context=model_context,
        threshold=threshold,
        system_prompt_tokens=system_prompt_tokens,
    ):
        return messages

    logger.info("Compressing %d messages using '%s' strategy", len(messages), strategy)

    if strategy == "sliding_window":
        result = compress_sliding_window(messages, keep_recent=keep_recent)
    elif strategy == "importance":
        result = compress_importance_based(messages, keep_recent=keep_recent)
    elif strategy == "semantic":
        result = compress_semantic(messages, keep_recent=keep_recent, model=model)
    else:  # "summarize" (default)
        return await compress_if_needed(
            messages,
            model=model,
            model_context=model_context,
            threshold=threshold,
            system_prompt_tokens=system_prompt_tokens,
            keep_recent=keep_recent,
        )

    logger.info(
        "Compressed (%s): %d → %d messages",
        strategy,
        len(messages),
        len(result),
    )
    return result
