"""Context compression — summarize old messages when approaching token limits.

Long conversations eventually exceed the model's context window. This module
detects when that's about to happen and compresses older messages into a
summary, preserving recent context verbatim.

Strategy (simpler than Hermes' multi-stage compressor):
  1. Estimate token count of the message history (chars / 4 heuristic)
  2. When it exceeds the threshold (default 80% of model's limit), trigger
  3. Keep the N most recent messages verbatim (default 10)
  4. Summarize everything before that into a single "system" message
  5. Replace old messages with [summary + recent messages]

The summary is generated by the same model the agent uses — no separate
summarizer model. This is a deliberate tradeoff: simpler architecture at
the cost of one extra API call per compression.

Cache safety: compression only touches message_history, never the system
prompt. The system prompt stays byte-stable for the entire conversation.
"""

from __future__ import annotations

import logging
from typing import Any

logger = logging.getLogger(__name__)

# Heuristic: 1 token ≈ 4 chars for English text
_CHARS_PER_TOKEN = 4

# Default thresholds
DEFAULT_MODEL_CONTEXT = 128_000  # tokens (gpt-4o standard)
DEFAULT_COMPRESS_THRESHOLD = 0.80  # compress at 80% of context window
DEFAULT_KEEP_RECENT = 10  # keep this many recent messages verbatim
DEFAULT_MIN_MESSAGES_TO_COMPRESS = 20  # don't compress if fewer than this


def estimate_tokens(text: str) -> int:
    """Rough token estimate: chars / 4. Good enough for threshold checks."""
    return max(1, len(text) // _CHARS_PER_TOKEN)


def estimate_message_tokens(messages: list[dict[str, str]]) -> int:
    """Estimate total tokens in a message list."""
    total = 0
    for msg in messages:
        content = msg.get("content", "")
        total += estimate_tokens(content)
        # Each message has ~4 tokens of overhead (role, separators)
        total += 4
    return total


def should_compress(
    messages: list[dict[str, str]],
    *,
    model_context: int = DEFAULT_MODEL_CONTEXT,
    threshold: float = DEFAULT_COMPRESS_THRESHOLD,
    system_prompt_tokens: int = 0,
) -> bool:
    """Check if message history should be compressed.

    Args:
        messages: List of {'role': ..., 'content': ...} dicts
        model_context: Model's max context window in tokens
        threshold: Fraction of context window that triggers compression
        system_prompt_tokens: Tokens used by the system prompt (reserved)

    Returns:
        True if compression is needed
    """
    if len(messages) < DEFAULT_MIN_MESSAGES_TO_COMPRESS:
        return False

    available = model_context - system_prompt_tokens
    trigger_at = int(available * threshold)
    current = estimate_message_tokens(messages)
    return current > trigger_at


def split_messages(
    messages: list[dict[str, str]],
    *,
    keep_recent: int = DEFAULT_KEEP_RECENT,
) -> tuple[list[dict[str, str]], list[dict[str, str]]]:
    """Split messages into (to_compress, to_keep).

    Args:
        messages: Full message history
        keep_recent: Number of recent messages to keep verbatim

    Returns:
        (old_messages, recent_messages) tuple
    """
    if len(messages) <= keep_recent:
        return [], messages
    return messages[:-keep_recent], messages[-keep_recent:]


def build_summary_prompt(old_messages: list[dict[str, str]]) -> str:
    """Build the prompt for the summarizer model.

    Args:
        old_messages: Messages to summarize

    Returns:
        Prompt string for the summarizer
    """
    conversation = "\n\n".join(
        f"[{m['role']}]: {m['content'][:2000]}"  # cap each message at 2000 chars
        for m in old_messages
        if m.get("content")
    )

    return (
        "Summarize the following conversation history concisely. "
        "Preserve key facts, decisions, code snippets, and action items. "
        "Keep it under 500 words. Write as a factual summary, not dialogue.\n\n"
        f"--- CONVERSATION TO SUMMARIZE ---\n{conversation}\n--- END ---"
    )


def compress_messages(
    messages: list[dict[str, str]],
    summary: str,
    *,
    keep_recent: int = DEFAULT_KEEP_RECENT,
) -> list[dict[str, str]]:
    """Replace old messages with a summary + recent messages.

    Args:
        messages: Full message history
        summary: Generated summary text
        keep_recent: Number of recent messages to keep verbatim

    Returns:
        New message list: [summary_message, ...recent_messages]
    """
    _, recent = split_messages(messages, keep_recent=keep_recent)

    summary_msg = {
        "role": "system",
        "content": (
            "[Context Summary — earlier conversation compressed]\n\n"
            f"{summary}\n\n"
            "[End of Summary — recent messages follow]"
        ),
    }

    return [summary_msg] + recent


async def compress_if_needed(
    messages: list[dict[str, str]],
    *,
    model: Any = None,
    model_context: int = DEFAULT_MODEL_CONTEXT,
    threshold: float = DEFAULT_COMPRESS_THRESHOLD,
    system_prompt_tokens: int = 0,
    keep_recent: int = DEFAULT_KEEP_RECENT,
) -> list[dict[str, str]]:
    """Compress message history if it exceeds the threshold.

    If compression is not needed, returns the original messages unchanged.
    If compression is needed but no model is provided, returns the original
    messages with a warning (graceful degradation).

    Args:
        messages: Message history
        model: Pydantic AI model instance for generating the summary
        model_context: Model's max context window
        threshold: Compression trigger fraction
        system_prompt_tokens: Tokens reserved by system prompt
        keep_recent: Messages to keep verbatim

    Returns:
        Potentially compressed message list
    """
    if not should_compress(
        messages,
        model_context=model_context,
        threshold=threshold,
        system_prompt_tokens=system_prompt_tokens,
    ):
        return messages

    old, recent = split_messages(messages, keep_recent=keep_recent)
    if not old:
        return messages

    logger.info(
        "Compressing %d messages (keeping %d recent, est. %d tokens)",
        len(old),
        len(recent),
        estimate_message_tokens(messages),
    )

    if model is None:
        logger.warning("Compression needed but no model provided — skipping")
        return messages

    # Generate summary using the model
    summary_prompt = build_summary_prompt(old)
    try:
        from pydantic_ai import Agent

        summarizer = Agent(
            model=model,
            system_prompt="You are a conversation summarizer. Be concise and factual.",
        )
        result = await summarizer.run(summary_prompt)
        summary = result.output
    except Exception as e:
        logger.warning("Summary generation failed: %s — skipping compression", e)
        return messages

    compressed = compress_messages(messages, summary, keep_recent=keep_recent)
    logger.info(
        "Compressed: %d messages → %d (est. %d tokens)",
        len(messages),
        len(compressed),
        estimate_message_tokens(compressed),
    )
    return compressed
